### ISSUE TITLE
numarator 163

### ISSUE THREAD

**Issue by botondkirei** [botondkirei/ELib#2]
Sunt curios cum functioneaza "Issues" in git. De aceea am  creat acest issue...

1. Am vazut ca in codul numaratorului acum este introdus si parametrul "delay". Daca tot apare acolo ar fi util ca mai jos unde sunt legate iesirile q(3..0) sa fie introdus acest parametru, de exemplu:

q(3) <= counter after delay;

2. La instantierea componentei "consumption_monitor", numarul iesirilor este legat la 15, cred ca 5 e destul.

**Comment by CherejaIulia** [comment]
Acolo cu 15 e o greseala. La ultima versiune stiu ca am cirectat ca am avut eroare la simulare. 

Trimis din Yahoo Mail pe Android 
 
  Pe joi, mai 24, 2018 la 18:19, botondkirei<notifications@github.com> a scris:   
Assigned #2 to @CherejaIulia.

**Comment by botondkirei** [comment]
Vad ca si ai primit.

**Comment by CherejaIulia** [comment]
Am primit, primesc pe mail dar am crezut ca e de la dvs .

Trimis din Yahoo Mail pe Android 
 
  Pe joi, mai 24, 2018 la 18:23, botondkirei<notifications@github.com> a scris:   Vad ca si ai primit.

**Comment by CherejaIulia** [comment]
Am rezolvat toate greselile. Scimbasem doar in proiectul meu si am uitat sa incarc si numaratorul.
Sa stergeti doar fisierul AutomatFinal.docx ca nu e bun.
Daca se mai schimba ceva, o sa schimb tot in celalalt sa ramana doar unul valid tot timpul.
Multumesc!

**Comment by botondkirei** [comment]
OK, ms. Am rezolvat,
